services:

  base-image:
    build:
      context: ./base-image
    image: e2e-project/base-image

  boomer:
    build:
      context: ./boomer
    networks:
      - local
    environment:
      ADDRESS: backend
    depends_on:
      - backend
      - base-image

  backend:
    build:
      context: ./backend
    ports:
      - "8181:8181" # remove after tests
    networks:
      - local
    depends_on:
      - base-image

  jenkins:
    ports:
      - "8080:8080"
      - "50000:50000"
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
      - type: bind
        source: /home/cflor/git
        target: /app/repos
    networks:
      - jenkins

  jenkins_slave:
    image: jenkins/inbound-agent:latest
    # build:
    #   context: ./jenkins-slave
    init: true
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=fa5177060800d613fea1886e087d51513d426106ff1a29ddb4bca831691c1044
      - JENKINS_AGENT_NAME=slave1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/jenkins-agent
    volumes:
      - type: volume
        source: jenkins-slave-data
        target: /var/jenkins
      - type: bind
        source: /home/cflor/git
        target: /app/repos
    networks:
      - jenkins
    depends_on:
      - jenkins
    ports:
      - 34700

  jenkins_slave_2:
    build:
      context: ./jenkins-slave
    init: true
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=85061b942c6a989b8d1b87e3c46d23205ad928bee85f023508e71408b1a67d44
      - JENKINS_AGENT_NAME=slave2
      - JENKINS_AGENT_WORKDIR=/home/jenkins/jenkins-agent
    volumes:
      - type: volume
        source: jenkins-slave-data
        target: /var/jenkins
      - type: bind
        source: /home/cflor/git
        target: /app/repos
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - jenkins
    depends_on:
      - jenkins
    ports:
      - 34700
      
  # spinnaker:
  #   build:
  #     context: ./spinnaker-image
  #     args:
  #       - PRIVATE_IP=172.20.0.13
  #       - MINNAKER_VERSION=0.1.3
  #   environment:
  #     - PRIVATE_IP=172.20.0.13
  #     - MINNAKER_VERSION=0.1.3
  #   networks:
  #     jenkins:
  #       ipv4_address: 172.20.0.13
  #   depends_on:
  #     - jenkins
  #   ports:
  #     - 5000:443
  #   volumes:
  #     - type: bind
  #       source: /sys/fs/cgroup
  #       target: /sys/fs/cgroup
  #       read_only: true
  #     - type: bind
  #       source: /sys/fs/cgroup/systemd
  #       target: /sys/fs/cgroup/systemd
  #   tmpfs:
  #     - /run
  #     - /tmp 
  #   privileged: true
  #   entrypoint: 
  #     - /lib/systemd/systemd

volumes:
  jenkins-data:
  jenkins-slave-data:


networks:
  local:
  jenkins:
    ipam:
      config:
        - subnet: 172.20.0.0/16


